### PR TITLE
Add github action specification

### LINKED ISSUE #1: Make a GitHub Action
This repo is interesting, a GitHub Action would be great for others to include in their profile page.

Currently, based on the implementation language, a docker image should do the trick. But ideally, using JavaScript/TypeScript will speed up a lot. That can be done in the future though.

I can help to do the first step.

### PR DESCRIPTION
**Pull request by frostming**
Close #1 

## Change summary

- Use delimiter pairs `<!--START_SECTION:my_github-->` and `<!--END:my_github-->` as placeholders
- Create a Dockerfile for Action. [Ref](https://docs.github.com/en/free-pro-team@latest/actions/creating-actions/creating-a-docker-container-action)
- Update workflow to use the new GitHub action

### CODE REVIEW

**Comment by frostming** [comment]
The script is already tested, but the action isn't. I am also the first time writing a custom action, there may still need some testing.

**Review by yihong0618 — APPROVED** [review]

**Comment by yihong0618** [comment]
Thank you very much. 
Will do some test, then merge~

**Comment by frostming** [comment]
Also, before publishing to the market, a dedicated README.md is needed for the action. The current content may need to move to another file or repository.

**Comment by yihong0618** [comment]
Got it.

**Pull request merged**
