### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by MoshiCoCo**
use `secrets.GITHUB_TOKEN` replace  `secrets.G_T`

### CODE REVIEW

**Comment by MoshiCoCo** [comment]
To be honest, the term G_T made me ambiguous, and I found out that it should be a GitHub token.

If G_T is a `personal access token ` created by the user, it should be stated in the document.


[GITHUB_TOKEN](https://docs.github.com/en/free-pro-team@latest/actions/reference/authentication-in-a-workflow#using-the-github_token-in-a-workflow)

**Comment by yihong0618** [comment]
@JunzhouLiu You are right. Because I used to use  secrets.GITHUB_TOKEN in another repo, so I choose secrets.G_T.
But for `GitHub Actions` one secret is enough.
Can you close this and take another pr, mention the `GITHUB_TOKEN` in README or  I will just merge this?

**Comment by MoshiCoCo** [comment]
> @JunzhouLiu You are right. Because I used to use secrets.GITHUB_TOKEN in another repo, so I choose secrets.G_T.
> But for `GitHub Actions` one secret is enough.
> Can you close this and take another pr, mention the `GITHUB_TOKEN` in README or I will just merge this?

I only modified the GitHub Actions configuration example in README

**Comment by yihong0618** [comment]
> > @JunzhouLiu You are right. Because I used to use secrets.GITHUB_TOKEN in another repo, so I choose secrets.G_T.
> > But for `GitHub Actions` one secret is enough.
> > Can you close this and take another pr, mention the `GITHUB_TOKEN` in README or I will just merge this?
> 
> I only modified the GitHub Actions configuration example in README

Merged, Thanks.

**Pull request merged**
